version: "3"
services:
  postgres:
    build: ./database
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  go-api:
    build: ./backend
    ports:
      - 8081:8081
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: todo
    links:
      - postgres